import * as THREE from 'three'
import { Wall } from '../entities/entityCreator'
import * as Graphics from '../graphcs/basicGraphics'
import {BaseModel} from './basemodel'
import {Position} from '../helpers/metrics'